[package]
name = "fdispatcher"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["cargo"] }
walkdir = "2.4.0"

[profile.release]
lto = true
opt-level = 'z'
debug = false

[[bin]]
name = "fd"
path = "src/main.rs"